subject: Biology
topic: Enzyme
diff_level:
  Remember: 3
  Understanding: 3
  Applying: 3
  Analyzing: 3

subtopic: Enzyme structure  # Optional: remove or comment out if not needed
num_questions: 12
past_exam_questions: ""    # optional

curriculum_file: Files/curriculum.txt
self_assessment_pdf: Files/Biology Revision & Self Assessment.pdf
reference_file: Files/APBiology-OP_5meoFaG.pdf
api_key: "...."
output_folder: "Output"
